package fr.unice.polytech.startingpoint.player.IA;

public enum HerosChoice {
    IChooseAHero,
    INeedGold,
    IDecideToAttack,
    IDecideToDefend,
    IDecideToProtectMyself,
    IDecideToBlockWinner,
    ThereAreNoMoreHeroesAttacking,
    ThereAreNoMoreHeroesDefence,
    IWantToChangeTheDistricts,
    ICanBuildSeveralDistrict,
    IOnlyHaveDuplicates,
    SoIChooseAHeroAtRandom,
    SoIChooseTheMagician,
    SoIChooseTheKing,
    SoIChooseTheMerchant,
    SoIChooseTheAssassin,
    SoIchooseTheThief,
    SoIchooseTheBishop,
    SoIchooseTheCondottiere,
    SoIChooseTheArchitect,
    WithNormalStrategy,
    WithPenultimateRoundStrategy,
    WithLastRoundStrategy,
    ImAboutToWin,
    SomeoneIsAboutToWin,
    PossibleWinnerIsBeforeMe,
    PossibleWinnerIsAfterMe,
    CondottiereIsNotAvailable,
    BishopIsNotAvailable,
    AssassinIsNotAvailable,
    MagicianIsNotAvailable,
    AllUsefulHeroesAreNotAvailable,
    AllUsefulHeroesAreAvailable,
    PossibleWinnerIsSecond;
}
